# Generated by Django 2.2.9 on 2020-07-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='MainUser',
        ),
    ]
